### ISSUE TITLE
Doesn't work with Apex 20.2

### ISSUE THREAD

**Issue by sokosp** [RonnyWeiss/APEX-Items-with-APEX-Buttons#1]
Hi Ronny and thanks for your great work.
We upgrade our Apex 20.1 app to latest 20.2 but the Icons don't work.
Have you tried it already?
![image](https://user-images.githubusercontent.com/21083416/97874335-c06d4180-1d10-11eb-9b5b-6f21f680fb0b.png)

**Comment by RonnyWeiss** [comment]
Hello

Did you checked that your static files are working correctly and that there are no others js errors on the page?

Because all my plug-ins are working fine in APEX 20.2 as you can see here: https://apex.oracle.com/pls/apex/f?p=103428:19

So please check for any other js error on the pages.

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
closed becauswe no reaction over a week
